name: BlueResExtension
version: '${project.version}'
main: net.mcblueice.blueresextension.BlueResExtension
api-version: 1.20
depend:
  - Residence
softdepend:
  - SafariNet
author: Blue
description: RES擴展
folia-supported: true
commands:
  blueresextension:
    description: BlueResExtension主指令
    usage: /blueresextension <reload|expand>

permissions:
  blueresextension.reload:
    description: 允許使用 /blueresextension reload
    default: op
  blueresextension.expandtool:
    description: 允許使用選取工具空揮預覽
    default: true
  blueresextension.expand:
    description: 允許使用 /blueresextension expand 顯示預計範圍
    default: true
