name: BlueResExtension
version: '${project.version}'
main: net.mcblueice.blueresextension.BlueResExtension
api-version: 1.20
depend:
  - Residence
softdepend:
  - SafariNet
author: Blue
description: RES擴展
commands:
  blueresextension:
    description: BlueResExtension主指令
    usage: /blueresextension <reload>

permissions:
  blueresextension.reload:
    description: 允許使用 /blueresextension reload
    default: op
